### ISSUE TITLE
Environmental Variables need Parentheses around them

### ISSUE THREAD

**Issue by schen70** [fermi-lat/AnalysisThreads#8]
In the PythonLikelihood.ipynb there's these lines for creating the model:

`from make4FGLxml import *
mymodel = srcList('./data/gll_psc_v26.xml','./data/PG1553_filtered_gti.fits','./data/PG1553_model.xml')
mymodel.makeModel('$FERMI_DIR/refdata/fermi/galdiffuse/gll_iem_v07.fits', 'gll_iem_v07', '$FERMI_DIR/refdata/fermi/galdiffuse/iso_P8R3_SOURCE_V3_v1.txt', 'iso_P8R3_SOURCE_V3_v1')`

However, without parentheses around FERMI_DIR the diffResps step runs into this error:

`File not found: $FERMI_DIR/refdata/fermi/galdiffuse/gll_iem_v07.fits
Caught St13runtime_error at the top level: File not found: $FERMI_DIR/refdata/fermi/galdiffuse/gll_iem_v07.fits`

Could the notebook be updated to prevent this error?

**Comment by joeastro** [comment]
Hello.

Thanks for letting us know about this issue. I've added to the parentheses to notebook as noted above, and it appears to work fine now. Closing issue.
